# Generated by Django 3.1 on 2023-06-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230603_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superadmin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_stuff',
        ),
    ]
